"""fixed tables

Revision ID: d2500d084bdd
Revises: 025c0c426cfa
Create Date: 2025-12-17 19:45:27.007276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2500d084bdd'
down_revision = '025c0c426cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_speakers',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_speakers_session_id_sessions')),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], name=op.f('fk_session_speakers_speaker_id_speakers')),
    sa.PrimaryKeyConstraint('session_id', 'speaker_id')
    )
    op.drop_table('session_speaker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_speaker',
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('speaker_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name='fk_session_speaker_session_id_sessions'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], name='fk_session_speaker_speaker_id_speakers'),
    sa.PrimaryKeyConstraint('session_id', 'speaker_id')
    )
    op.drop_table('session_speakers')
    # ### end Alembic commands ###
